# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Formulize docs

# Short description (goes below the title; it will also be used in the RSS feed)
description: Formulize docs

# Your name, as you want it to appear underneath each post and in the footer
author: Julian Egelstaff

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: /formulize

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://jegelstaff.github.io/formulize/

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: formulize/:title